apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-api
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-operator
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-runner
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- if .Values.pocSiem.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-siem-adapter
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-siem-sink
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
