apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-api
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-operator
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: malzone-runner
  labels:
    {{- include "malzone.labels" . | nindent 4 }}
automountServiceAccountToken: false
